# src/main/resources/application-docker.yml
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/user_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: appuser
    password: securepass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  data:
    redis:
      host: redis
      port: 6379